package:
  name: gtftk
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.2.0"

source:
  #fn: ggrepel_0.6.5.tar.gz
  #url:
  #  - fn: ggtp://cran.r-project.org/src/contrib/ggrepel_0.6.5.tar.gz

  # You can add a hash for the file here, like md5 or sha1
  #md5: 7e2732cd4840efe2dc9e4bc689cf1ee5
  #sha1: 73316bb68042eafc04bc21473e414f220dd403b1
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  #number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/
    - lib64/

# Suggests: knitr, rmarkdown
requirements:
  build:
    - zlib
    - python >=2.7,<3
    - argparse
    - nose
    - bats
    - r-ggplot2
    - r-reshape2
    - r-data.table
    - r-plyr
    - bedtools ==2.27.1
    - r-base ==3.4.1
    - cloudpickle >=0.4.0
    - ftputil >=3.3.1
    - pandas >=0.19.2,<0.20 # 0.20 removes the 'replace' attribute for 'pandas._libs.interval.Interval' object.
    - pybedtools >=0.7.8
    - pybigwig >=0.2.8
    - pysam >=0.9.1.4
    - pyyaml >=3.12
    - gcc # [not win]
    - sphinx_bootstrap_theme >=0.4.9
    - sphinxcontrib-programoutput >=0.8
    - sphinx >=1.5.2
    - requests >=2.13.0
    - cffi >=1.10.0
    - pyparsing >=2.2.0
    - biopython >=1.69
  run:
    - zlib
    - python >=2.7,<3
    - argparse
    - nose
    - bats
    - r
    - r-ggplot2
    - r-reshape2
    - r-data.table
    - r-plyr
    - bedtools ==2.27.1
    - cloudpickle >=0.4.0
    - ftputil >=3.3.1
    - pandas >=0.19.2,<0.20 # 0.20 removes the 'replace' attribute for 'pandas._libs.interval.Interval' object.
    - pybedtools >=0.7.8
    - pybigwig >=0.2.8
    - pysam >=0.9.1.4
    - pyyaml >=3.12
    - gcc # [not win]
    - sphinx_bootstrap_theme >=0.4.9
    - sphinxcontrib-programoutput >=0.8
    - sphinx >=1.5.2
    - requests >=2.13.0
    - cffi >=1.10.0
    - pyparsing >=2.2.0
    - biopython >=1.69
    
test:
  commands:
    # You can put additional test commands to be run here.
    #- $R -e "library('ggrepel')" # [not win]
    #- "\"%R%\" -e \"library('ggrepel')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home: http://github.com/slowkow/ggrepel
  #license: GPL-2
  summary: 'The gtftk suite.'


# The original CRAN metadata for this package was:

# Package: ggrepel
# Version: 0.5
# Authors@R: c(person("Kamil", "Slowikowski", role = c("aut", "cre"), email = "kslowikowski@fas.harvard.edu"))
# Title: Repulsive Text and Label Geoms for 'ggplot2'
# Description:  Provides text and label geoms for 'ggplot2' that help to avoid overlapping text labels. Labels repel away from each other and away from the data points.
# Depends: R (>= 3.0.0), ggplot2 (>= 2.0.0)
# Imports: grid, Rcpp
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# License: GPL-2
# URL: http://github.com/slowkow/ggrepel
# BugReports: http://github.com/slowkow/ggrepel/issues
# RoxygenNote: 5.0.1
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Packaged: 2016-02-08 13:56:35 UTC; slowikow
# Author: Kamil Slowikowski [aut, cre]
# Maintainer: Kamil Slowikowski <kslowikowski@fas.harvard.edu>
# Repository: CRAN
# Date/Publication: 2016-02-08 15:39:34

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
