{% set version = "0.9.8" %}

package:
  name: pygtftk
  version: '{{ version }}'

source:
  git_url: 'https://github.com/dputhier/pygtftk'
  #url: 'https://github.com/dputhier/pygtftk/archive/v{{ version }}.tar.gz'
  #sha256: 88b920d0fea7e7a7f796b0b03986226a094f8bdd590d9723663ae8dab4032c38

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6,<3.7
    - zlib
  run:
    - python >=3.6,<3.7
    - cython
    - argparse
    - bedtools ==2.27.1
    - cloudpickle >=0.4.0
    - ftputil >=3.3.1,<4.0.0
    - numpy
    - pandas >=0.23.3
    - scipy >=1.1.0
    - pybedtools >=0.7.8
    - pybigwig >=0.3
    - pyyaml >=3.12
    - requests >=2.13.0
    - cffi >=1.10.0
    - pyparsing >=2.2.0
    - biopython >=1.69
    - zlib
    - matplotlib >=2.0.2
    - plotnine >=0.4.0
    - future

test:
  imports:
    - pygtftk
  commands:
    - gtftk -h
  requires:
    - nose
    - bats
    - unzip
    - coreutils
    - perl

about:
  home: http://github.com/dputhier/pygtftk
  license: MIT
  summary: 'The gtftk suite providing facilities to manipulate genomic annotations in gtf format.'

