package:
  name: pygtftk
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.2.0"

source:
  #fn: ggrepel_0.6.5.tar.gz
  #url:
  #  - fn: ggtp://cran.r-project.org/src/contrib/ggrepel_0.6.5.tar.gz

  # You can add a hash for the file here, like md5 or sha1
  #md5: 7e2732cd4840efe2dc9e4bc689cf1ee5
  #sha1: 73316bb68042eafc04bc21473e414f220dd403b1
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  #number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/
    - lib64/

# Suggests: knitr, rmarkdown
requirements:
  build:
    - GitPython >=2.1.8
    - python >=2.7,<3
    - pyparsing
    - argparse
    - nose
    - bats
    - bedtools ==2.27.1
    - cloudpickle >=0.4.0
    - ftputil >=3.3.1
    - pandas >=0.23.3
    - scipy >=1.1.0
    - pybedtools >=0.7.8
    - pybigwig >=0.2.8
    - pysam >=0.9.1.4
    - pyyaml >=3.12
    - gcc >=4.8.5
    - sphinx_bootstrap_theme >=0.4.9
    - sphinxcontrib-programoutput >=0.8
    - sphinx >=1.5.2
    - requests >=2.13.0
    - cffi >=1.10.0
    - pyparsing >=2.2.0
    - biopython >=1.69
    - zlib <1.2.8-3
    - matplotlib >=2.0.2
    - plotnine >=0.4.0
    - libstdcxx-ng >=7.2.0
    - unzip
    - gawk

  run:
    - GitPython >=2.1.8
    - python >=2.7,<3
    - pyparsing
    - argparse
    - nose
    - bats
    - bedtools ==2.27.1
    - cloudpickle >=0.4.0
    - ftputil >=3.3.1
    - pandas >=0.23.3
    - scipy >=1.1.0
    - pybedtools >=0.7.8
    - pybigwig >=0.2.8
    - pysam >=0.9.1.4
    - pyyaml >=3.12
    - gcc >=4.8.5
    - sphinx_bootstrap_theme >=0.4.9
    - sphinxcontrib-programoutput >=0.8
    - sphinx >=1.5.2
    - requests >=2.13.0
    - cffi >=1.10.0
    - pyparsing >=2.2.0
    - biopython >=1.69
    - zlib <1.2.8-3
    - matplotlib >=2.0.2
    - plotnine >=0.4.0
    - libstdcxx-ng >=7.2.0
    - unzip
    - gawk

test:
  commands:
    # You can put additional test commands to be run here.
    #- $R -e "library('ggrepel')" # [not win]
    #- "\"%R%\" -e \"library('ggrepel')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/dputhier/pygtftk
  license: MIT
  summary: 'The gtftk suite.'


